# Site settings
title: A Blog
header-img: img/home-bg.jpg
email: miguel.rueda@outlook.com
description: "The blog description goes here"
baseurl: ""
url: "http://yourdomain.com"
# twitter_username: SBootstrap
github_username:  miguelrueda
facebook_username:  miguelrueda

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
