# Site settings
title: Android Blog
header-img: img/android_bg.jpg
email: miguel.rueda@outlook.com
description: "The blog description goes here"
baseurl: ""
url: ""
# twitter_username: SBootstrap
github_username:  miguelrueda
facebook_username:  miguel.rueda.91

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
